export interface FlashcardData {
  id: number;
  category: string;
  name: string;
  description: string;
  useCase: string;
  icon: string;
}

export const flashcards: FlashcardData[] = [
  // Compute
  { id: 1, category: "Compute", name: "Amazon EC2", description: "Virtual servers in the cloud. Provides resizable compute capacity to run your applications.", useCase: "Hosting a custom web application, a legacy database, or running a game server that requires full OS-level access.", icon: "💻" },
  { id: 2, category: "Compute", name: "AWS Lambda", description: "Run code without thinking about servers (Serverless). You pay only for the compute time you consume.", useCase: "Automatically resizing images as soon as a user uploads them to an S3 bucket, without keeping a server running 24/7.", icon: "⚡" },
  { id: 3, category: "Compute", name: "Amazon ECS", description: "Elastic Container Service. A highly scalable, fast container management service for Docker.", useCase: "Running a microservices architecture where each service is packaged in a Docker container.", icon: "📦" },
  { id: 4, category: "Compute", name: "Amazon EKS", description: "Elastic Kubernetes Service. A managed service to run Kubernetes easily on AWS.", useCase: "Migrating an existing on-premises Kubernetes cluster to the cloud without changing your deployment tools.", icon: "☸️" },
  { id: 5, category: "Compute", name: "AWS Fargate", description: "Serverless compute engine for containers that works with both ECS and EKS.", useCase: "Running containerized apps without wanting to manage, patch, or scale the underlying EC2 instances.", icon: "☁️" },
  { id: 6, category: "Compute", name: "AWS Elastic Beanstalk", description: "An easy-to-use service for deploying and scaling web applications and services.", useCase: "A developer wants to upload their Java or Node.js code and have AWS automatically handle the deployment, load balancing, and scaling.", icon: "🌱" },
  { id: 7, category: "Compute", name: "Amazon EC2 Auto Scaling", description: "Automatically adds or removes EC2 instances according to conditions you define.", useCase: "Adding more web servers automatically during a Black Friday sale to handle traffic, and removing them when traffic drops.", icon: "📈" },
  { id: 8, category: "Compute", name: "AWS Lightsail", description: "Easy-to-use cloud resources to get your web application or website up and running quickly.", useCase: "A small business wanting to quickly launch a simple WordPress blog with predictable monthly pricing.", icon: "💡" },

  // Storage
  { id: 9, category: "Storage", name: "Amazon S3", description: "Simple Storage Service. Scalable object storage for data backup, archival, and analytics.", useCase: "Storing user-uploaded profile pictures, videos, or hosting static website assets (HTML/CSS/JS).", icon: "🪣" },
  { id: 10, category: "Storage", name: "Amazon EBS", description: "Elastic Block Store. High-performance block storage volumes for use with EC2 instances.", useCase: "Providing the primary boot drive (C: drive or root volume) for an EC2 instance running a database.", icon: "💽" },
  { id: 11, category: "Storage", name: "Amazon EFS", description: "Elastic File System. Serverless, fully elastic file storage for use with AWS Cloud services.", useCase: "Sharing a common file system across multiple EC2 instances, like a shared media folder for a fleet of web servers.", icon: "📁" },
  { id: 12, category: "Storage", name: "Amazon S3 Glacier", description: "Secure, durable, and extremely low-cost Amazon S3 storage classes for data archiving.", useCase: "Storing years of compliance logs or medical records that are rarely accessed but must be kept legally.", icon: "🧊" },
  { id: 13, category: "Storage", name: "AWS Storage Gateway", description: "Hybrid cloud storage service that gives you on-premises access to virtually unlimited cloud storage.", useCase: "An on-premises office server seamlessly backing up its local files to AWS S3 in the background.", icon: "🌉" },

  // Database
  { id: 14, category: "Database", name: "Amazon RDS", description: "Relational Database Service. Set up, operate, and scale a relational database in the cloud.", useCase: "Running a traditional MySQL or PostgreSQL database for an e-commerce site without managing backups manually.", icon: "🗄️" },
  { id: 15, category: "Database", name: "Amazon DynamoDB", description: "Fast, flexible NoSQL database service for single-digit millisecond performance at any scale.", useCase: "Storing player profiles and high scores for a globally popular mobile game with millions of users.", icon: "⚡" },
  { id: 16, category: "Database", name: "Amazon Aurora", description: "MySQL and PostgreSQL-compatible relational database built for the cloud with high performance.", useCase: "An enterprise needing a database that is 5x faster than standard MySQL with built-in fault tolerance.", icon: "🌅" },
  { id: 17, category: "Database", name: "Amazon Redshift", description: "Fast, simple, cost-effective data warehousing to analyze all your data using standard SQL.", useCase: "Analyzing petabytes of sales data to generate complex business intelligence reports for executives.", icon: "📊" },
  { id: 18, category: "Database", name: "Amazon ElastiCache", description: "Fully managed, in-memory caching service supporting flexible, real-time use cases.", useCase: "Caching the most frequently viewed products on a website to reduce database load and speed up page loads.", icon: "🚀" },

  // Networking & Content Delivery
  { id: 19, category: "Networking", name: "Amazon VPC", description: "Virtual Private Cloud. Provision a logically isolated section of the AWS Cloud.", useCase: "Creating a secure, private network for your company's backend servers so they cannot be accessed directly from the public internet.", icon: "🌐" },
  { id: 20, category: "Networking", name: "Amazon Route 53", description: "A highly available and scalable cloud Domain Name System (DNS) web service.", useCase: "Registering a domain name (like myapp.com) and routing users to the correct AWS resources when they type it in.", icon: "🗺️" },
  { id: 21, category: "Networking", name: "Amazon CloudFront", description: "Fast content delivery network (CDN) service that securely delivers data, videos, and APIs globally.", useCase: "Caching your website's images and videos in edge locations worldwide so users in Tokyo and New York load them instantly.", icon: "⚡" },
  { id: 22, category: "Networking", name: "Elastic Load Balancing (ELB)", description: "Automatically distributes incoming application traffic across multiple targets, such as EC2 instances.", useCase: "Spreading incoming web traffic evenly across 5 different EC2 instances so no single server gets overwhelmed.", icon: "⚖️" },
  { id: 23, category: "Networking", name: "Amazon API Gateway", description: "Create, publish, maintain, monitor, and secure APIs at any scale.", useCase: "Creating a secure entry point (API) for a mobile app to communicate with backend AWS Lambda functions.", icon: "🚪" },

  // Security, Identity, & Compliance
  { id: 24, category: "Security", name: "AWS IAM", description: "Identity and Access Management. Securely manage access to AWS services and resources.", useCase: "Creating individual user accounts for your developers and giving them permission to access only specific S3 buckets.", icon: "🔑" },
  { id: 25, category: "Security", name: "Amazon Cognito", description: "Add user sign-up, sign-in, and access control to your web and mobile apps quickly and easily.", useCase: "Adding a 'Login with Google/Facebook' button and user registration system to your mobile app.", icon: "👤" },
  { id: 26, category: "Security", name: "AWS KMS", description: "Key Management Service. Create and manage cryptographic keys and control their use.", useCase: "Encrypting sensitive customer credit card data in your database using keys managed securely by AWS.", icon: "🔐" },
  { id: 27, category: "Security", name: "AWS Shield", description: "Managed Distributed Denial of Service (DDoS) protection service that safeguards applications.", useCase: "Protecting your online store from being taken offline by a massive botnet attack.", icon: "🛡️" },
  { id: 28, category: "Security", name: "AWS WAF", description: "Web Application Firewall that helps protect your web applications or APIs against common web exploits.", useCase: "Blocking malicious IP addresses or preventing SQL injection attacks against your web application.", icon: "🔥" },
  { id: 29, category: "Security", name: "Amazon GuardDuty", description: "Intelligent threat detection service that continuously monitors for malicious activity.", useCase: "Getting an alert if someone is trying to access your AWS account from an unusual location or IP address.", icon: "👁️" },
  { id: 30, category: "Security", name: "AWS Artifact", description: "Your go-to, central resource for compliance-related information that matters to you.", useCase: "Downloading AWS's ISO or SOC compliance reports to prove to an auditor that your cloud infrastructure is secure.", icon: "📜" },
  { id: 43, category: "Security", name: "Amazon Macie", description: "Fully managed data security and data privacy service that uses machine learning to discover and protect your sensitive data.", useCase: "Automatically scanning your S3 buckets to find and alert you if employees accidentally uploaded unencrypted files containing Social Security Numbers.", icon: "🕵️" },
  { id: 44, category: "Security", name: "Amazon Inspector", description: "Automated vulnerability management service that continually scans AWS workloads for software vulnerabilities.", useCase: "Scanning your EC2 instances to find out if they are running outdated software with known security flaws.", icon: "🔍" },

  // Management & Governance
  { id: 31, category: "Management", name: "Amazon CloudWatch", description: "Monitoring and observability service built for DevOps engineers, developers, and IT managers.", useCase: "Setting up an alarm to send you an email if your EC2 instance's CPU usage goes over 90%.", icon: "⏱️" },
  { id: 32, category: "Management", name: "AWS CloudTrail", description: "Track user activity and API usage. Enables governance, compliance, and operational auditing.", useCase: "Investigating exactly which user deleted a critical database table and at what time.", icon: "👣" },
  { id: 33, category: "Management", name: "AWS CloudFormation", description: "Infrastructure as Code (IaC). Model and provision all your cloud infrastructure resources.", useCase: "Writing a template file to automatically deploy an entire environment (VPC, EC2, RDS) in minutes instead of clicking through the console.", icon: "🏗️" },
  { id: 34, category: "Management", name: "AWS Trusted Advisor", description: "An online tool that provides real-time guidance to help you provision your resources following AWS best practices.", useCase: "Getting a recommendation to close an open security port or to downgrade an underutilized EC2 instance to save money.", icon: "🦉" },
  { id: 35, category: "Management", name: "AWS Cost Explorer", description: "An easy-to-use interface that lets you visualize, understand, and manage your AWS costs and usage over time.", useCase: "Creating a graph to see exactly how much money your team spent on S3 storage over the last 6 months.", icon: "💰" },
  { id: 45, category: "Management", name: "AWS Organizations", description: "Account management service that enables you to consolidate multiple AWS accounts into an organization that you create and centrally manage.", useCase: "A large company managing 50 different AWS accounts for different departments and paying for them all on a single consolidated bill.", icon: "🏢" },
  { id: 46, category: "Management", name: "AWS Control Tower", description: "Provides the easiest way to set up and govern a secure, multi-account AWS environment.", useCase: "Setting up a new AWS environment for a company with built-in security guardrails and best practices applied automatically.", icon: "🗼" },

  // Integration & Messaging
  { id: 36, category: "Integration", name: "Amazon SNS", description: "Simple Notification Service. Fully managed pub/sub messaging, SMS, email, and mobile push notifications.", useCase: "Sending a text message (SMS) or email alert to IT staff when a server goes down.", icon: "🔔" },
  { id: 37, category: "Integration", name: "Amazon SQS", description: "Simple Queue Service. Fully managed message queuing for microservices, distributed systems, and serverless applications.", useCase: "Holding thousands of customer orders in a queue during a flash sale so the backend database doesn't crash while processing them.", icon: "📥" },
  { id: 38, category: "Integration", name: "Amazon EventBridge", description: "Serverless event bus that makes it easier to build event-driven applications at scale.", useCase: "Triggering a Lambda function automatically every time a new user is added to your database.", icon: "🎭" },
  { id: 39, category: "Integration", name: "AWS Step Functions", description: "Visual workflow service that helps developers use AWS services to build distributed applications.", useCase: "Orchestrating a complex order fulfillment process: charge credit card, then update inventory, then send shipping email.", icon: "🛤️" },

  // Analytics & Machine Learning
  { id: 40, category: "Analytics & ML", name: "Amazon Athena", description: "Interactive query service that makes it easy to analyze data in Amazon S3 using standard SQL.", useCase: "Running SQL queries directly on CSV files stored in S3 without needing to load them into a database first.", icon: "🔍" },
  { id: 41, category: "Analytics & ML", name: "Amazon EMR", description: "Cloud big data platform for processing vast amounts of data using open source tools like Apache Spark.", useCase: "Processing massive amounts of genomic data or financial transactions using a managed Hadoop cluster.", icon: "🐘" },
  { id: 42, category: "Analytics & ML", name: "Amazon SageMaker", description: "Fully managed service that provides every developer and data scientist with the ability to build, train, and deploy ML models.", useCase: "A data scientist building and training a custom AI model to predict customer churn based on historical data.", icon: "🧠" },
  { id: 47, category: "Analytics & ML", name: "Amazon Rekognition", description: "Makes it easy to add image and video analysis to your applications using proven, highly scalable, deep learning technology.", useCase: "Automatically detecting faces, objects, or inappropriate content in user-uploaded photos.", icon: "👁️" },
  { id: 48, category: "Analytics & ML", name: "Amazon Polly", description: "Service that turns text into lifelike speech, allowing you to create applications that talk.", useCase: "Converting blog posts into audio podcasts automatically using natural-sounding AI voices.", icon: "🗣️" },
  { id: 49, category: "Analytics & ML", name: "Amazon Transcribe", description: "Automatically convert speech to text using deep learning process called automatic speech recognition (ASR).", useCase: "Generating automatic subtitles for video lectures or transcribing customer service phone calls.", icon: "🎙️" },
  { id: 50, category: "Analytics & ML", name: "Amazon Translate", description: "Neural machine translation service that delivers fast, high-quality, affordable, and customizable language translation.", useCase: "Translating a website's product reviews from English to Spanish in real-time.", icon: "🌍" },

  // Developer Tools
  { id: 51, category: "Developer Tools", name: "AWS CodeCommit", description: "Secure, highly scalable, managed source control service that hosts private Git repositories.", useCase: "Hosting your company's private source code securely within the AWS ecosystem (similar to GitHub).", icon: "🗃️" },
  { id: 52, category: "Developer Tools", name: "AWS CodeBuild", description: "Fully managed continuous integration service that compiles source code, runs tests, and produces software packages.", useCase: "Automatically compiling your Java code and running unit tests every time a developer pushes a new commit.", icon: "🏗️" },
  { id: 53, category: "Developer Tools", name: "AWS CodeDeploy", description: "Fully managed deployment service that automates software deployments to a variety of compute services.", useCase: "Automatically deploying the latest version of your app to a fleet of 100 EC2 instances without downtime.", icon: "🚀" },
  { id: 54, category: "Developer Tools", name: "AWS CodePipeline", description: "Fully managed continuous delivery service that helps you automate your release pipelines.", useCase: "Creating a workflow that automatically pulls code from CodeCommit, builds it in CodeBuild, and deploys it via CodeDeploy.", icon: "🛤️" },
  { id: 55, category: "Developer Tools", name: "AWS Cloud9", description: "Cloud-based integrated development environment (IDE) that lets you write, run, and debug your code with just a browser.", useCase: "Writing and debugging code from a Chromebook or iPad using only a web browser.", icon: "💻" },
  { id: 56, category: "Developer Tools", name: "AWS X-Ray", description: "Helps developers analyze and debug production, distributed applications, such as those built using a microservices architecture.", useCase: "Tracing a user request as it travels through API Gateway, Lambda, and DynamoDB to find out exactly where a bottleneck is occurring.", icon: "🩻" }
];
